FYP/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    #url(r'^$', include('webapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^webapp/', include('webapp.urls')),
    url(r'^modeltraining/', include('modeltraining.urls')),
]

webapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'webapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^auth/', views.auth, name='auth'),
    url(r'^callback/', views.callback, name='callback'),
    url(r'^followers/', views.followers, name='followers'),
    url(r'^auth_followers/', views.auth_followers, name='auth_followers'),
    url(r'^followers_callback/', views.followers_callback, name='followers_callback'),
    # url(r'^oauth/authorize/$', views.authorize, name='oauth_authorize'),
    # url(r'^oauth/callback/$', views.callback, name='oauth_callback'),
]

webapp/models.py
from django.db import models

class users_app(models.Model):
    id = models.BigIntegerField(default=0, primary_key=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    screen_name = models.CharField(max_length=200, blank=True, null=True)
    statuses_count = models.IntegerField(default=0, blank=True, null=True)
    followers_count = models.IntegerField(default=0, blank=True, null=True)
    friends_count = models.IntegerField(default=0, blank=True, null=True)
    favourites_count = models.IntegerField(default=0, blank=True, null=True)
    listed_count = models.IntegerField(default=0, blank=True, null=True)
    created_at = models.CharField(max_length=200, blank=True, null=True)
    url = models.CharField(max_length=200, blank=True, null=True)
    lang = models.CharField(max_length=200, blank=True, null=True)
    time_zone = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    default_profile = models.CharField(max_length=200, blank=True, null=True)
    default_profile_image = models.CharField(max_length=200, blank=True, null=True)
    geo_enabled = models.CharField(max_length=200, blank=True, null=True)
    profile_image_url = models.CharField(max_length=200, blank=True, null=True)
    profile_banner_url = models.CharField(max_length=200, blank=True, null=True)
    profile_use_background_image = models.CharField(max_length=200, blank=True, null=True)
    profile_background_image_url_https = models.CharField(max_length=500, blank=True, null=True)
    profile_text_color = models.CharField(max_length=200, blank=True, null=True)
    profile_image_url_https = models.CharField(max_length=200, blank=True, null=True)
    profile_sidebar_border_color = models.CharField(max_length=200, blank=True, null=True)
    profile_background_tile = models.CharField(max_length=200, blank=True, null=True)
    profile_sidebar_fill_color = models.CharField(max_length=200, blank=True, null=True)
    profile_background_image_url = models.CharField(max_length=200, blank=True, null=True)
    profile_background_color = models.CharField(max_length=200, blank=True, null=True)
    profile_link_color = models.CharField(max_length=200, blank=True, null=True)
    utc_offset = models.CharField(max_length=200, blank=True, null=True)
    protected = models.CharField(max_length=200, blank=True, null=True)
    verified = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    bot = models.NullBooleanField(default=None)


class tweets_app(models.Model):
    created_at = models.CharField(max_length=200, blank=True, null=True)
    id = models.BigIntegerField(default=0, primary_key=True)
    text = models.CharField(max_length=1000, blank=True, null=True)
    source = models.CharField(max_length=200, blank=True, null=True)
    user_id = models.IntegerField(default=0, blank=True, null=True)
    truncated = models.CharField(max_length=200, blank=True, null=True)
    in_reply_to_status_id = models.BigIntegerField(default=0, blank=True, null=True)
    in_reply_to_user_id = models.BigIntegerField(default=0, blank=True, null=True)
    in_reply_to_screen_name = models.CharField(max_length=200, blank=True, null=True)
    geo = models.CharField(max_length=200, blank=True, null=True)
    retweet_count = models.IntegerField(default=0, blank=True, null=True)
    favorite_count = models.IntegerField(default=0, blank=True, null=True)
    num_hashtags = models.IntegerField(default=0, blank=True, null=True)
    num_urls = models.IntegerField(default=0, blank=True, null=True)
    num_mentions = models.IntegerField(default=0, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    lang = models.CharField(max_length=200, blank=True, null=True)
    bot = models.NullBooleanField(default=None)


class followers_app(models.Model):
    following_id = models.BigIntegerField(default=0, blank=True, null=True)
    id = models.BigIntegerField(default=0, primary_key=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    screen_name = models.CharField(max_length=200, blank=True, null=True)
    statuses_count = models.IntegerField(default=0, blank=True, null=True)
    followers_count = models.IntegerField(default=0, blank=True, null=True)
    friends_count = models.IntegerField(default=0, blank=True, null=True)
    favourites_count = models.IntegerField(default=0, blank=True, null=True)

webapp/views.py
from django.shortcuts import render, redirect
from textblob import TextBlob
from webapp.models import *
import pickle
import numpy as np
import tweepy
import pandas as pd
import datetime

# consumer key and secret to access the twitter api
consumer_token = "zwGPR1XN0wtllYEdbZyhKwJzX"
consumer_secret = "Ob5zlQFPl0eUUHoqj9ZUrYxWM9dFgrxE3Oz17ljqtvV4TuQwMR"


# function to go onto the home page
def index(request):
    return render(request, 'webapp/index.html')


# function to authenticate the request to access the twitter api
def auth(request):

    # checks to make sure that the method of the request has been a post method and gets the twitter handle of user
    if request.method == "POST":
        handle = request.POST["TwitterHandle"]
        request.session["TwitterHandle"] = handle

    # creating the oauth handler and specifying the callback request
    oauth = tweepy.OAuthHandler(consumer_token, consumer_secret, 'http://localhost/webapp/callback')

    # try except block to validate the redirect api for the oauth handler
    try:
        redirect_url = oauth.get_authorization_url()

        request.session['request_token'] = oauth.request_token

        return redirect(redirect_url)

    # except in the case of auth no validated
    except tweepy.TweepError:
        context = {
            'problem': 'Verifier for twitter error'
        }
        print('Error! Failed to get request token.')
        return render(request, 'webapp/error.html', context)


# function for authenticating the request to get a users twitter followers with access to the api
def auth_followers(request):

    # checks to make sure that the method of the request has been a post method and gets the twitter handle of user
    if request.method == "POST":
        handle = request.POST["TwitterHandle_f"]
        request.session["TwitterHandle_f"] = handle

    # creating the oauth handler and specifying the callback request
    oauth = tweepy.OAuthHandler(consumer_token, consumer_secret, 'http://localhost/webapp/followers_callback')#http://192.168.1.12/webapp/followers_callback

    # try except block to validate the redirect api for the oauth handler
    try:
        redirect_url = oauth.get_authorization_url()

        request.session['request_token'] = oauth.request_token

        return redirect(redirect_url)

    # except in the case of auth no validated
    except tweepy.TweepError:
        context = {
            'problem': 'Verifier for twitter error'
        }
        print('Error! Failed to get request token.')
        return render(request, 'webapp/error.html', context)


# function to accept the callback from the oauth authentication for checking a user
def callback(request):

    # check to make sure the handle has been successfully stored in the session
    if 'TwitterHandle' in request.session:
        # getting the oauth and handle
        handle = request.session['TwitterHandle']
        verifier = request.GET.get('oauth_verifier')

        auth = tweepy.OAuthHandler(consumer_token, consumer_secret)
        token = request.session.get('request_token')
        # request.session.delete('request_token')
        auth.request_token = token

        # try except block to validate the oauth
        try:
            auth.get_access_token(verifier)
            api = tweepy.API(auth)

            user = api.get_user(handle)

            user_id, lang = insert_user_data(user)

            tweets = []

            tweets_200 = api.user_timeline(screen_name=handle, count=200)

            # check to make sure that some tweets have been successfully returned from the api
            if tweets_200:

                print(len(tweets_200))

                tweets.extend(tweets_200)

                realign = tweets[-1].id - 1

                # for loop to get 1000 of the most recent tweets from the user
                for i in range(0, 4):
                    tweets_200 = api.user_timeline(screen_name=handle, count=200, max_id=realign)

                    tweets.extend(tweets_200)
                    realign = tweets[-1].id - 1

                tweets_200 = api.user_timeline(screen_name=handle, count=1, max_id=realign)

                tweets.extend(tweets_200)
                print(len(tweets))

                insert_tweet_data(tweets, lang, user_id)

            # calling the prediction class to check the user
            prediction, user_df, sentiment_df, timing, sum_tweets, average_tweets, num_tweets = rf_user_prediction(user_id, handle)

            # this is the context to return variables to the html UI
            context = {
                'prediction': prediction,
                'handle': handle,
                'status_count': user_df.iloc[0][0],
                'followers_count': user_df.iloc[0][1],
                'friends_count': user_df.iloc[0][2],
                'favourite_count': user_df.iloc[0][3],
                'positive': sentiment_df[0],
                'neutral': sentiment_df[1],
                'negative': sentiment_df[2],
                'threeAM': timing[0],
                'sixAm': timing[1],
                'nineAm': timing[2],
                'twelvePm': timing[3],
                'threePm': timing[4],
                'sixPm': timing[5],
                'ninePm': timing[6],
                'twelveAm': timing[7],
                'sumRetweet': sum_tweets[0],
                'sumHashtag': sum_tweets[1],
                'sumUrl': sum_tweets[2],
                'sumMentions': sum_tweets[3],
                'averageRetweet': average_tweets[0],
                'averageHashtag': average_tweets[1],
                'averageUrl': average_tweets[2],
                'averageMentions': average_tweets[3],
                'num_tweets': num_tweets
            }

            # renders the web page template for user prediction
            return render(request, 'webapp/prediction.html', context)
        except tweepy.TweepError:
            context = {
                'problem': 'Verifier for twitter error'
            }
            return render(request, 'webapp/error.html', context)

    # check if there is no handle in the session
    else:
        context = {
            'problem': 'Twitter Handle not passed in'
        }
        return render(request, 'webapp/error.html', context)


# function to insert the user data into the web app database so that the prediction can access the data
def insert_user_data(user_data):
    user = users_app(id=user_data.id, name=strip_non_ascii(user_data.name), screen_name=user_data.screen_name,
                     statuses_count=user_data.statuses_count, followers_count=user_data.followers_count,
                     friends_count=user_data.friends_count, favourites_count=user_data.favourites_count,
                     listed_count=user_data.listed_count, created_at=user_data.created_at, url=user_data.url,
                     lang=user_data.lang, time_zone=user_data.time_zone, location=user_data.location,
                     default_profile=user_data.default_profile, default_profile_image=user_data.default_profile_image,
                     geo_enabled=user_data.geo_enabled, profile_image_url=user_data.profile_image_url,
                     profile_use_background_image=user_data.profile_use_background_image,
                     profile_background_image_url_https=user_data.profile_background_image_url_https,
                     profile_text_color=user_data.profile_text_color, profile_image_url_https=user_data.profile_image_url_https,
                     profile_sidebar_border_color=user_data.profile_sidebar_border_color, profile_background_tile=user_data.profile_background_tile,
                     profile_sidebar_fill_color=user_data.profile_sidebar_fill_color, profile_background_image_url=user_data.profile_background_image_url,
                     profile_background_color=user_data.profile_background_color, profile_link_color=user_data.profile_link_color,
                     utc_offset=user_data.utc_offset, protected=user_data.protected, verified=user_data.verified,
                     description=user_data.description)

    user.save()
    return user.id, user.lang


# function to insert users followers data into the web app database so the prediction can access the data
def insert_followers_data(main_user_id, user_data):
    user = followers_app(following_id=main_user_id, id=user_data.id, name=strip_non_ascii(user_data.name),
                         screen_name=user_data.screen_name, statuses_count=user_data.statuses_count,
                         followers_count=user_data.followers_count, friends_count=user_data.friends_count,
                         favourites_count=user_data.favourites_count)

    user.save()


# function to insert the users tweet data into th web app database so the prediction can access the data
def insert_tweet_data(tweets, lang, user_id):
    for tweet in tweets:
        utf = strip_non_ascii(tweet.text)

        tweet_data = tweets_app(created_at=tweet.created_at, id=tweet.id, text=utf, source=tweet.source,
                                user_id=user_id, truncated=tweet.truncated, in_reply_to_status_id=tweet.in_reply_to_status_id,
                                in_reply_to_user_id=tweet.in_reply_to_user_id, in_reply_to_screen_name=tweet.in_reply_to_screen_name,
                                retweet_count=tweet.retweet_count,
                                favorite_count=tweet.favorite_count,
                                num_hashtags=len(tweet.entities['hashtags']), num_urls=len(tweet.entities['urls']),
                                num_mentions=len(tweet.entities['user_mentions']), lang=lang)
        tweet_data.save()


# function that takes in the user id and handle as passed arguments
# the function then loads the prediction models and performs the necessary prediction on the data
def rf_user_prediction(user_id, handle):
    rf_user_filename = 'random_forest_user_model.sav'
    rf_sentiment_filename = 'sentiment_model.sav'

templates/webapp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>

    {% load staticfiles %}
    {% load static %}
{#    <link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">#}
{#    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">#}
{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/style.css' %}" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <style>
        #wrapper {
          padding-left: 250px;
          transition: all 0.4s ease 0s;
          margin-top: 40px;
        }

        #sidebar-wrapper {
          margin-left: -250px;
          left: 250px;
          width: 250px;
          background: #000;
          position: fixed;
          height: 100%;
          overflow-y: auto;
          z-index: 1000;
          transition: all 0.4s ease 0s;
        }

        #wrapper.active {
          padding-left: 0;
        }

        #wrapper.active #sidebar-wrapper {
          left: 0;
        }

        #page-content-wrapper {
          width: 100%;
        }



        .sidebar-nav {
          position: absolute;
          top: 0;
          width: 250px;
          list-style: none;
          margin: 0;
          padding: 0;
        }

        .sidebar-nav li {
          line-height: 40px;
          text-indent: 20px;
        }

        .sidebar-nav li a {
          color: #999999;
          display: block;
          text-decoration: none;
          padding-left: 60px;
        }

        .sidebar-nav li a span:before {
          position: absolute;
          left: 0;
          color: #41484c;
          text-align: center;
          width: 20px;
          line-height: 18px;
        }

        .sidebar-nav li a:hover,
        .sidebar-nav li.active {
          color: #fff;
          background: rgba(255,255,255,0.2);
          text-decoration: none;
        }

        .sidebar-nav li a:active,
        .sidebar-nav li a:focus {
          text-decoration: none;
        }

        .sidebar-nav > .sidebar-brand {
          height: 65px;
          line-height: 60px;
          font-size: 18px;
        }

        .sidebar-nav > .sidebar-brand a {
          color: #999999;
        }

        .sidebar-nav > .sidebar-brand a:hover {
          color: #fff;
          background: none;
        }

        .content-header h1 {
          margin: 0;
          margin-left: 20px;
          line-height: 65px;
          display: inline-block;
        }

        .inset {
          padding: 20px;
        }

        @media (max-width:767px) {

            #wrapper {
                padding-left: 0;
            }

            #sidebar-wrapper {
                left: 0;
            }

            #wrapper.active {
                position: relative;
                left: 250px;
            }

            #wrapper.active #sidebar-wrapper {
                left: 250px;
                width: 250px;
                transition: all 0.4s ease 0s;
            }

            .inset {
                padding: 15px;
            }
        }
    </style>
</head>
<body background="{% static 'webapp/images/ep_naturalwhite.png' %}">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webapp:index' %}">BotYou</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'webapp:index' %}">Test User<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'webapp:followers'%}">Test Followers</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="page-header" style="margin-top: 100px" align="center">
      <h1 class="text-center">An Error has occured, Please return to the main screen.</h1>
      <p>{{ problem }}</p>
      <a align="center" href="{% url 'webapp:index' %}" class="btn btn-default">Home</a>
    </div>


</body>
</html>

templates/webapp/followers.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>BotYou</title>


    {% load staticfiles %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


</head>

<body class="w3-light-grey" background="{% static 'webapp/images/ep_naturalwhite.png' %}">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webapp:index' %}">BotYou</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'webapp:index' %}">Test User<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'webapp:followers'%}">Test Followers</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="page-header">
      <h1 class="text-center">Test Users Followers</h1>
    </div>


    <div class="w3-display-middle w3-padding w3-col l6 m8">
        <div class="w3-container w3-blue">
          <h2><i class="fa fa-twitter w3-margin-right"></i>Please Enter Twitter Handle</h2>
        </div>
        <div class="w3-container w3-white w3-padding-16">
          <form action="{% url 'webapp:auth_followers' %}" method = "post">
              {% csrf_token %}
              <div class="w3-row-padding" style="margin:0 -16px;">
                  <div class="w3-half w3-margin-bottom">
                    <label><i class="fa fa-twitter"></i> Twitter Handle</label>
                    <input class="w3-input w3-border" type="text" placeholder="@Twitter_Handle" name="TwitterHandle_f" required>
                  </div>
              </div>
              <button class="w3-button w3-blue" type="submit"><i class="fa fa-search w3-margin-right"></i> Check Users Followers</button>
          </form>
        </div>
    </div>

</body>
</html>

templates/webapp/index.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>BotYou</title>


    {% load staticfiles %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


</head>

<body class="w3-light-grey" background="{% static 'webapp/images/ep_naturalwhite.png' %}">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webapp:index' %}">BotYou</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'webapp:index' %}">Test User<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'webapp:followers'%}">Test Followers</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <div class="page-header">
      <h1 class="text-center">User Prediction</h1>
    </div>

{#        <img class="w3-image" src="http://cdn.wonderfulengineering.com/wp-content/uploads/2014/03/high-resolution-wallpapers-12.jpg" style="min-width:1000px" width="1500" height="800">#}
        <div class="w3-display-middle w3-padding w3-col l6 m8">
            <div class="w3-container w3-blue">
              <h2><i class="fa fa-twitter w3-margin-right"></i>Please Enter Twitter Handle</h2>
            </div>
            <div class="w3-container w3-white w3-padding-16">
              <form action="{% url 'webapp:auth' %}" method = "post">
                  {% csrf_token %}
                  <div class="w3-row-padding" style="margin:0 -16px;">
                      <div class="w3-half w3-margin-bottom">
                        <label><i class="fa fa-twitter"></i> Twitter Handle</label>
                        <input class="w3-input w3-border" type="text" placeholder="@Twitter_Handle" name="TwitterHandle" required>
                      </div>
                  </div>
                  <button class="w3-button w3-blue" type="submit"><i class="fa fa-search w3-margin-right"></i> Check User</button>
              </form>
            </div>
        </div>

</body>
</html>